### ISSUE TITLE
Adjusted golden ratio line-height doesn't render unless forcing an update

### ISSUE THREAD

**Issue by nschappl** [lorenzwoehr/Golden-Ratio-Line-Height-Sketch-Plugin#1]
Below is an example of what I'm seeing using some example 18px text in a 300px wide box. I hit cmd-L and the line height adjusts to something that is quite obviously too much. At that time, the line-height field in the inspector (side-panel) still says that the line height is 18px. However, as soon as I increase the line height by 1 the line-height in the inspector instantly changes to 27px and the text visually updates. Then, I can decrease the line height by 1 to return the line height to its appropriate 26px line height (according to the golden ratio rules). Any idea what is preventing the text from updating directly after the cmd-L (without the extra steps)?  

<img width="361" alt="screen shot 2016-03-24 at 10 34 47 pm" src="https://cloud.githubusercontent.com/assets/889753/14036574/be3c214a-f210-11e5-8d20-654ac74de80e.png">

**Comment by wonderment** [comment]
+1 We're experiencing this issue as well.

**Comment by lorenzwoehr** [comment]
Thanks for submitting this issue!
1. Which version of Sketch are you using? 
2. Do you use any other plugins triggered by cmd-L? (Especially affecting the line height)
3. Do you experience the same issue when launching the plugin from the plugin menu, not using the shortcut?
4. @nschappl Using the same text box from your example: After using the plugin, please select a different layer and then select the text box again (so the UI updates)... What line height is it?

**Comment by nschappl** [comment]
1. Skype version 3.6.1.
2. No other plugins triggered by cmd-L.
3. Yes, the same exact behavior occurs when using the menu directly rather than the shortcut.
4. After using the plugin, then selecting a different layer, then returning to the text box, the line height is correctly shown as "24" in the inspector (right sidebar), but the actual text line height (graphics) are not updated and still look like the middle text in my original image.

Thank you for taking a look!

**Comment by wonderment** [comment]
Here's a video demo illustrating the issue: https://youtu.be/DYR0HjCA4g0

**Comment by lorenzwoehr** [comment]
The problem is caused by the new version of sketch... 
I´ll release a new version within a few days. 

Thank you for your help!

**Comment by George-Hill** [comment]
Hey, love this plugin so far! Appreciate the work, any luck on the bug-free version? :) Thanks

**Comment by lorenzwoehr** [comment]
@George-Hill Thanks! As this bug is caused by Sketch itself, and not by this plugin, I´m still waiting for an update...

**Comment by lorenzwoehr** [comment]
Finally found a fix. Thanks for your patience! @nschappl @wonderment @George-Hill
